### ISSUE TITLE
boto level logging

### ISSUE THREAD

**Issue by marcioemiranda** [awslabs/aws-lambda-powertools#21]
Hello Heitor,

I am using samplig rate for my logger. An annoying side effect is that when it's enabled, it gets flooded with boto debug logs.

I took a look in the code and found a boto_level parameter in the setup function under aws_lambda_logging.py. I assume if I set this parameter to a different level then it would solve this problem.

Can I set this up via the logger_setup function in logger.py?

**Comment by marcioemiranda** [comment]
I've taken a look at the other issues..

Looks like this is a duplicate of #16

**Comment by heitorlessa** [comment]
Thanks for reporting this, Marcio - I’ll prioritise to get this done by the
end of the week.

I’ll likely use POWERTOOLS_LOG_LEVEL to make it more explicit, and prevent
these annoying side effects

**Comment by heitorlessa** [comment]
This is now fixed in 0.8.0 - Here's what you need to do.

* Use the new `Logger` as opposed to `logger_setup` and `logger_inject_lambda_context`
* If you want to enable DEBUG for the whole package, use `set_package_logger` function
* The new Logger isolates and doesn't propagate any logging configuration, and you have full control over the logger if you wish to make any modifications

---

```python
```
